### ISSUE TITLE
AstraMC projector

### ISSUE THREAD

**Issue by epapoutsellis** [TomographicImaging/CIL-ASTRA#54]
Currently, norm for the AstraMC 2D operator is not working
see [here](
https://github.com/vais-ral/CCPi-astra/blob/master/Wrappers/Python/ccpi/astra/operators/AstraProjectorMC.py#L65).The reason is because in the master the lines are commented out.

Did we decide, how we want to treat this case?

**Comment by jakobsj** [comment]
I'm not sure, but I was thinking we could replace the MC versions
completely by having the user use the ChannelwiseOperator with
AstraProjectorSimple. Then everything should work automatically and we
avoid maintaining any MC code.

**Comment by epapoutsellis** [comment]
``` python
from ccpi.framework import ImageGeometry, AcquisitionGeometry
from ccpi.optimisation.operators import ChannelwiseOperator
from ccpi.astra.operators import AstraProjectorMC, AstraProjectorSimple
from timeit import default_timer as timer
import numpy as np

chan = 80

ig = ImageGeometry(voxel_num_x = 100, 
                   voxel_num_y = 100,
                   voxel_size_x = 1., 
                   voxel_size_y = 1., 
                   channels = chan,
                   dimension_labels = ['channel','horizontal_y','horizontal_x'])

ag = AcquisitionGeometry('cone',
                         '2D',
                         np.linspace(0,np.pi,100),
                         pixel_num_h = 100,
                         pixel_size_h = 1,                           
                         dist_source_center = 10, 
                         dist_center_detector = 10,
                         channels = chan,
                         dimension_labels = ['channel', 'angle', 'horizontal'])

Aop1 = AstraProjectorMC(ig, ag, 'cpu')


igtmp = ig.clone()
igtmp.shape = ig.shape[1:]
igtmp.dimension_labels = ['horizontal_y', 'horizontal_x']
igtmp.channels = 1

agtmp = ag.clone()
agtmp.shape = ag.shape[1:]
agtmp.dimension_labels = ['angle', 'horizontal']
agtmp.channels = 1

Aop2 = ChannelwiseOperator(AstraProjectorSimple(igtmp, agtmp, 'cpu'), chan)

x = ig.allocate('random')

t1 = timer()
#a1 = Aop1.norm()
a1 = Aop1.direct(x)
t2 = timer()
print(t2 - t1)

t3 = timer()
#a2 = Aop2.norm()
a2 = Aop2.direct(x)
t4 = timer()
print(t4 - t3)

np.testing.assert_array_almost_equal(a1.as_array(),a2.as_array(), decimal = 4)

```

It works with Channelwise and have no problem replacing. The only thing is that I do not like doing the tmp trick for geometries. We need somehow to recover geometries without channels

**Comment by jakobsj** [comment]
Agree. Can subset do it? I mean for a multichannel data set we can obtain a
specific single channel data set by subset with e.g. channel=1. Will
something like subset be possible just for geometries? In fact, subset must
modify the geometry as part of the dataset it's working on, how does it do
that?

**Comment by gfardell** [comment]
Subset should give you a geometry consistent with the slice you are using.

However  this is going to copy the data to a new container. Maybe we just want a pointer to the start of the data we're interested in?

**Comment by jakobsj** [comment]
We don't really need to handle any data. From one geometry with multiple
channels we want to neatly create a new geometry (no data) which is
identical apart from not having any channels. Having the user to create
this single-channel geometry is inconvenient.

If there is no simple way to do this, a workaround could be to keep the
AstraMC projector and as input take the MC geometries. Then in  __init__ do
the generation of the corresponding single-channel geometry, store the
number of channels and use ChannelwiseOperator and AstraProjectorSimple to
set it up. That would be quite neat actually. Then the user needs not worry
about anything other than saying create me an AstraMC projector, without
having to know about ChannelwiseOperator and single-channel geometries.

**Comment by gfardell** [comment]
If we are saying the astra projectors won't run across channels then we could move this inside the projector operator, it could take the full geometry in but just set it up with channel=1? I'm not sure if that's logical behaviour though. I guess as long as there was a warning it'd work.

I also think it'd be good to have an option that removes the choice of projector from the user. We could choose what to do ourselves based on the AG. if it's passed channel data it runs channelwise. For example the new AstraProjectorFlexible doesn't care if it's passed a 2D or 3D dataset at the moment... although this is still a wip.

Just as a note, in the new geometry shape and labels will be updated automatically once channels is set equal to 1. So I think it'll look neater then anyway.

**Comment by gfardell** [comment]
ProjectionOperator now handles multichannel data with the ChannelwiseOperator so I am closing this issue.
