### ISSUE TITLE
FBP missing filter_type argument

### ISSUE THREAD

**Issue by epapoutsellis** [TomographicImaging/CIL-ASTRA#86]
The `FBP` class has no information about the `filter_type`.  To select different `filters` need to use `FBP_simple`.

**Comment by gfardell** [comment]
ASTRA's FDK for vector geometry doesn't (currently) support different filter types. This is the one we wrap for both cone and parallel.

**Comment by gfardell** [comment]
We can now use the CIL recon class to set custom filters and should encourage this rather than further wrapping Astra
